Bottleneck
Cython
PyYAML
aplpy 
asdf
astrocut
astrodendro
astropy
astroquery
corner 
dill
dust-extinction
emcee
glue-astronomy
glue-core
glue-jupyter
glue-vispy-viewers
gwcs
h5py
healpy
ipyvue
ipyvuetify
ipywidgets
joblib
juliet 
jupyter
jwst
lmfit
matplotlib
mplcursors
munch
notebook
numpy
oifits
pandas
photutils
poppy
pysiaf
pysynphot
pyyaml
scikit-image
scipy
seaborn 
shapely
spectral-cube 
specutils
termcolor
uncertainties
webbpsf
git+https://github.com/astropy/regions.git
git+https://github.com/radio-astro-tools/radio-beam.git
jdaviz
git+https://github.com/spacetelescope/jwst@0.17.0#egg
git+https://github.com/spacetelescope/jwst_gtvt.git
git+https://github.com/spacetelescope/mirage#egg
