name: deploy-book

#  Only run this when the master branch changes
on:
  push:
    branches:
    - main
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**
    paths:
      - 'notebooks/**.ipynb'

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:       
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

   # - name: Install dependencies
   #   run: |
   #     pip install -r CIenvironment.yml

    - name: Install Python dependencies
      run: |
        sudo apt-get install python3-pip
        #        pip install git+git://github.com/executablebookproject/cli.git
        pip install ghp-import
        pip install jupyter-book
        pip install myst-nb
        pip install nbval
        PATH="${PATH}:${HOME}/.local/bin"
        
    - name: nbval validation step
      run: |
        python -m pytest --nbval --durations 10
        
    - name: Build book TOC file 
      run: |
        jupyter-book toc from-project ./notebooks
    - name: Build book HTML 
      run: |
        jupyter-book build .
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
